apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config-logging
  labels:
    app.kubernetes.io/part-of: knative-operator
    operator.knative.dev/release: v1.6.0
  {{- include "chart.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configLogging.Example | quote }}