apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-knative-eventing-operator-aggregated
  labels:
    app.kubernetes.io/part-of: knative-operator
    operator.knative.dev/release: v1.6.0
  {{- include "chart.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-knative-eventing-operator-aggregated
  labels:
    app.kubernetes.io/part-of: knative-operator
    operator.knative.dev/release: v1.6.0
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-knative-eventing-operator-aggregated'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'